/**
 * Built-in theme definitions.
 * Each theme provides the full set of CSS variable values.
 * Hover/active variants are included explicitly for built-in themes
 * to ensure pixel-perfect fidelity.
 */

export const BUILTIN_THEMES = {
  classic: {
    id: 'classic',
    name: 'Classic',
    builtIn: true,
    variables: {
      '--bg-primary': '#1a2125',
      '--bg-primary-rgb': '26, 33, 37',
      '--bg-secondary': '#111619',
      '--bg-body': '#73885c',
      '--bg-body-color': '#939e7f',
      '--bg-body-image': 'url("../images/bg.png")',
      '--bg-hover': '#2f3c43',
      '--bg-selected': '#3a4952',
      '--bg-odd-row': '#222c31',
      '--bg-header': '#000',
      '--bg-restricted': '#2e343c',
      '--bg-player-hover': '#1b2328',
      '--btn-primary': '#244967',
      '--btn-primary-hover': '#2f5e85',
      '--btn-primary-active': '#193449',
      '--btn-disabled': '#3e3e3e',
      '--btn-danger': '#c13535',
      '--btn-danger-hover': '#cf5050',
      '--btn-danger-active': '#a12c2c',
      '--btn-success': '#3a9933',
      '--btn-success-hover': '#46b83d',
      '--btn-success-active': '#2e7a29',
      '--btn-cancel': '#db2a2a',
      '--btn-cancel-hover': '#e14d4d',
      '--btn-cancel-active': '#bc2020',
      '--btn-info': '#4444dd',
      '--btn-info-hover': '#6767e3',
      '--btn-info-active': '#2626d2',
      '--text-primary': '#fff',
      '--text-secondary': '#bfbfbf',
      '--text-link': '#ffe7cc',
      '--text-admin': '#ffdb72',
      '--text-notice': '#8ed2ab',
      '--text-muted': '#888',
      '--text-rec-active': '#d33',
      '--text-dark': '#000',
      '--team-red': '#e56e56',
      '--team-blue': '#5689e5',
      '--team-red-text': '#ff8686',
      '--team-blue-text': '#b7b7ff',
      '--border-accent': '#c13535',
      '--border-input-focus': '#244967',
      '--separator-color': 'gray',
      '--scrollbar-thumb': '#445661',
      '--scrollbar-thumb-hover': '#59717f',
      '--scrollbar-alt': '#708b9b',
      '--slider-thumb': '#389cdb',
      '--slider-track': 'rgba(255, 255, 255, .3)',
      '--sound-slider-bar': '#cad4da',
      '--sound-slider-bar-hover': '#f7f9f9',
      '--autocomplete-bg': '#fff',
      '--autocomplete-hover': '#d1e2fe',
      '--autocomplete-selected': '#b3c6ff',
      '--timebar-bg': '#393737',
      '--timebar-progress': '#5c5c5c',
      '--timebar-marker': '#cecece',
      '--game-popup-overlay': 'rgba(115, 136, 92, .5)',
      '--overlay-dark': 'rgba(0, 0, 0, .7)',
    }
  },

  midnight: {
    id: 'midnight',
    name: 'Midnight',
    builtIn: true,
    variables: {
      '--bg-primary': '#141427',
      '--bg-primary-rgb': '20, 20, 39',
      '--bg-secondary': '#0e0e1f',
      '--bg-body': '#1a1a3e',
      '--bg-body-color': '#2a2a4a',
      '--bg-body-image': 'none',
      '--bg-hover': '#252547',
      '--bg-selected': '#302e5c',
      '--bg-odd-row': '#1a1a33',
      '--bg-header': '#0a0a14',
      '--bg-restricted': '#1e1e3a',
      '--bg-player-hover': '#181830',
      '--btn-primary': '#3d3d8f',
      '--btn-primary-hover': '#5252a8',
      '--btn-primary-active': '#2e2e70',
      '--btn-disabled': '#2a2a3e',
      '--btn-danger': '#9b2c2c',
      '--btn-danger-hover': '#b83d3d',
      '--btn-danger-active': '#7a2222',
      '--btn-success': '#2d7b46',
      '--btn-success-hover': '#389957',
      '--btn-success-active': '#226038',
      '--btn-cancel': '#b82a2a',
      '--btn-cancel-hover': '#d14545',
      '--btn-cancel-active': '#8f2020',
      '--btn-info': '#5b5bd6',
      '--btn-info-hover': '#7474e0',
      '--btn-info-active': '#4444b3',
      '--text-primary': '#e8e8f0',
      '--text-secondary': '#9999b8',
      '--text-link': '#c9a0e8',
      '--text-admin': '#f0d070',
      '--text-notice': '#70c8a0',
      '--text-muted': '#666688',
      '--text-rec-active': '#e84040',
      '--text-dark': '#0a0a14',
      '--team-red': '#e06050',
      '--team-blue': '#6080e0',
      '--team-red-text': '#ff8888',
      '--team-blue-text': '#aaaaff',
      '--border-accent': '#7b68ee',
      '--border-input-focus': '#5050a0',
      '--separator-color': '#404060',
      '--scrollbar-thumb': '#3a3a5e',
      '--scrollbar-thumb-hover': '#50507a',
      '--scrollbar-alt': '#5a5a8a',
      '--slider-thumb': '#7b68ee',
      '--slider-track': 'rgba(200, 200, 255, .25)',
      '--sound-slider-bar': '#8888b0',
      '--sound-slider-bar-hover': '#b0b0d0',
      '--autocomplete-bg': '#e0e0f0',
      '--autocomplete-hover': '#c8c8e8',
      '--autocomplete-selected': '#a8a8d8',
      '--timebar-bg': '#1a1a30',
      '--timebar-progress': '#3a3a60',
      '--timebar-marker': '#8888aa',
      '--game-popup-overlay': 'rgba(40, 30, 80, .5)',
      '--overlay-dark': 'rgba(0, 0, 0, .75)',
    }
  },

  emerald: {
    id: 'emerald',
    name: 'Emerald',
    builtIn: true,
    variables: {
      '--bg-primary': '#172420',
      '--bg-primary-rgb': '23, 36, 32',
      '--bg-secondary': '#0f1c18',
      '--bg-body': '#1a3a2e',
      '--bg-body-color': '#2a4a3a',
      '--bg-body-image': 'none',
      '--bg-hover': '#243a32',
      '--bg-selected': '#2e4a3e',
      '--bg-odd-row': '#1c2e28',
      '--bg-header': '#0a1410',
      '--bg-restricted': '#1e3028',
      '--bg-player-hover': '#1a2a24',
      '--btn-primary': '#1e6e4a',
      '--btn-primary-hover': '#28885c',
      '--btn-primary-active': '#16573b',
      '--btn-disabled': '#2a3832',
      '--btn-danger': '#a83030',
      '--btn-danger-hover': '#c44444',
      '--btn-danger-active': '#882424',
      '--btn-success': '#28a060',
      '--btn-success-hover': '#32c074',
      '--btn-success-active': '#1e7a4a',
      '--btn-cancel': '#c83030',
      '--btn-cancel-hover': '#e04848',
      '--btn-cancel-active': '#a02424',
      '--btn-info': '#2288aa',
      '--btn-info-hover': '#30a0c4',
      '--btn-info-active': '#1a6e88',
      '--text-primary': '#e0f0e8',
      '--text-secondary': '#90b0a0',
      '--text-link': '#a0d8b0',
      '--text-admin': '#e8d070',
      '--text-notice': '#60d8a0',
      '--text-muted': '#608878',
      '--text-rec-active': '#e04040',
      '--text-dark': '#0a140e',
      '--team-red': '#e06050',
      '--team-blue': '#5090e0',
      '--team-red-text': '#ff8888',
      '--team-blue-text': '#88b8ff',
      '--border-accent': '#2ecc71',
      '--border-input-focus': '#1e6e4a',
      '--separator-color': '#305040',
      '--scrollbar-thumb': '#305040',
      '--scrollbar-thumb-hover': '#407060',
      '--scrollbar-alt': '#508868',
      '--slider-thumb': '#2ecc71',
      '--slider-track': 'rgba(200, 255, 220, .25)',
      '--sound-slider-bar': '#88c0a0',
      '--sound-slider-bar-hover': '#b0e0c8',
      '--autocomplete-bg': '#e0f0e8',
      '--autocomplete-hover': '#c0e0d0',
      '--autocomplete-selected': '#a0d0b8',
      '--timebar-bg': '#1a2e24',
      '--timebar-progress': '#305040',
      '--timebar-marker': '#88aa98',
      '--game-popup-overlay': 'rgba(30, 80, 50, .5)',
      '--overlay-dark': 'rgba(0, 0, 0, .75)',
    }
  }
};

export const DEFAULT_THEME_ID = 'classic';

/** Get a built-in theme by its ID */
export function getBuiltInTheme(id) {
  return BUILTIN_THEMES[id] || null;
}

/** Get all built-in theme IDs and names */
export function getBuiltInThemeList() {
  return Object.values(BUILTIN_THEMES).map(t => ({ id: t.id, name: t.name }));
}
